# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Özgür Yazılım Locası"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "hakkında"
    href:           "//ytuoyl.github.io/hakkinda"
  - name:           "twitter"
    href:           "//twitter.com/ytuoyl"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
